name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SITE_NAME: Auto Crónica
      NEXT_PUBLIC_SITE_CONTACT_EMAIL: contact@autocronica.autos
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3001
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run test:cov
      - run: npm run build
